### ISSUE TITLE
Delete empty lines / blocks

### ISSUE THREAD

**Issue by QWxleA** [hyrijk/logseq-plugin-split-block#1]
The plugin works (extremely) well, and has been a great help to quickly add stuff to my graph. The only problem so far is if I import:
```markdow
Line one

Line two
```
It transforms it to:
```markdown
- line one
- 
- line two
```
There is no good reason for the empty block to exist, it's just a remnant of a poorly formatted source block.

Expected end result:
```markdown
- line one
- line two
```
It is not a major problem, it would just save some time.

**Comment by hyrijk** [comment]
Version 1.2.0 filters out blank lines，just update it :)
