### ISSUE TITLE
broken since 0.66 (Mac)

### ISSUE THREAD

**Issue by Simeonh2021** [hyrijk/logseq-plugin-split-block#3]
the plugin no longer works since 0.66 (macos), at least after 220422nightly version

**Comment by hyrijk** [comment]
@Simeonh2021 tested it on my m1 macbook air and it works. Could you  send me some text to try to reproduce the problem?

**Comment by Simeonh2021** [comment]
> @Simeonh2021 tested it on my m1 macbook air and it works. Could you send me some text to try to reproduce the problem?
![Uploading 50A94763-27D3-49EA-9BF4-38BF8F4AC9B6.gif…]()

**Comment by Simeonh2021** [comment]
> @Simeonh2021 tested it on my m1 macbook air and it works. Could you send me some text to try to reproduce the problem?

updated to logseq arm version 220426 nightly. Issue is still there.

if I type slash command and click split block, nothing happens.

if I right click the left button of a block (with multiple lines in the text) and click "split block", the whole block disappeared! 

![C3721522-16AE-4C8F-8716-02BB28EE2244](https://user-images.githubusercontent.com/90461274/165680136-ce9aa113-8264-40a8-8d12-b93d5580f814.gif)

**Comment by hyrijk** [comment]
Try the [latest nightly version](https://github.com/logseq/logseq/releases/tag/nightly). If still have problems, press option+command+I to open DevTools and see if there are any errors reported

**Comment by Simeonh2021** [comment]
Thank you. It works in 0.67
